export const filtersListSimulations = [
  {
    id: "0",
    header: "Sélection",
    name: "selection",
    type: "",
    options: [],
    isUser: true,
    value: "",
    disabled: true,
    domain:["simulations","archives"],
  },
  {
    id: "1",
    header: "Date",
    name: "creationDate",
    type: "text",
    options: [],
    isUser: true,
    value: "",
    disabled: false,
    domain:["simulations","archives"],
  },
  {
    id: "2",
    header: "Etape du dossier",
    name: "folderStep",
    type: "radio",
    options: ["simulation", "chantier"],
    isUser: true,
    value: "",
    disabled: false,
    domain:["simulations","archives"],
  },
  {
    id: "3",
    header: "Devis à générer",
    name: "quoteStatus",
    type: "empty",
    options: [],
    isUser: true,
    value: "0",
    disabled: false,
    domain:["simulations","archives"],
  },
  {
    id: "4",
    header: "Devis en cours de rédaction",
    name: "quoteStatus",
    type: "empty",
    options: [],
    isUser: true,
    value: "1",
    disabled: false,
    domain:["simulations","archives"],
  },
  {
    id: "5",
    header: "Devis rédigés en vérification Batikal ",
    name: "quoteStatus",
    type: "checkbox",
    options: ["En attente de validation", "Anomalie", "Validé"],
    isUser: true,
    value: [],
    disabled: false,
    domain:["simulations","archives"],
  },
  {
    id: "6",
    header: "Devis signés en vérification Batikal ",
    name: "quoteStatus",
    type: "checkbox",
    options: ["En attente de validation", "Anomalie", "Validé"],
    isUser: true,
    value: [],
    disabled: false,
    domain:["simulations","archives"],
  },
  {
    id: "7",
    header: "Chantier -N° dossier CEE",
    name: "foldCEENumber",
    type: "numeric",
    options: [],
    isUser: true,
    value: "",
    disabled: false,
    domain:["simulations","archives"],
  },
  {
    id: "8",
    header: "Partenaire",
    name: "partner_Name",
    type: "text",
    options: [],
    isUser: false,
    value: "",
    disabled: false,
    domain:["simulations","archives"],
  },
  {
    id: "9",
    header: "Dossiers supprimés",
    name: "fieldsDeleted",
    type: "empty",
    options: [],
    isUser: false,
    value: "",
    disabled: false,
    domain:["simulations","archives"],
  },
  {
    id: "10",
    header: "Motif",
    name: "reason",
    type: "radio",
    options: ["Abandon client", "Non éligible", "Dossier clôturé"],
    isUser: true,
    disabled: false,
    domain: ["archives"],
  },
];
