export const accountFields = [
  {
    id: 0,
    header: "Nom de la société ",
    name:"societyName",
    type: "text",
    placeholder: "Unitech",
    required: true,
  },
  {
    id: 1,
    header: "Adresse ",
    name:"address",
    type: "text",
    placeholder: "20 rue de la paix",
    required: true,
  },
  {
    id: 2,
    header: "Code postal et ville ",
    name:"postalCodeCity",
    type: "text",
    placeholder: "93100 Bobigny",
    required: true,
  },
  {
    id: 3,
    header: "Email ",
    name:"emailSociety",
    type: "Email",
    placeholder: "secretariat.direction@unitech.com",
    required: true,
  },
  {
    id: 4,
    header: "N° TVA Intracommunautaire ",
    name:"TVA",
    type: "text",
    placeholder: "FR896587136542",
    required: true,
  },
  {
    id: 5,
    header: "N° SIRET ",
    name:"siret",
    type: "text",
    placeholder: "896521478965",
    required: true,
  },
  {
    id: 6,
    header: "Code NAF ",
    name:"NAFcode",
    type: "text",
    placeholder: "4120B",
    required: true,
  },
  {
    id: 7,
    header: "RCS ",
    name:"RCS",
    type: "text",
    placeholder: "Bobigny",
    required: true,
  },
  {
    id: 8,
    header: "Assurance décennale ",
    name:"decennial_insurance",
    type: "text",
    placeholder: "GENERALI",
  },
  {
    id: 9,
    header: "Autre information ",
    name:"other_information",
    type: "text",
    placeholder: "RGE : QPAC/526521",
  },
];
